function display_menu()
% to show the different options
disp(' *********************************************')
disp('          COMPRESSIBLE FLOW TOOL')
disp('   (C. Airiau, 2012 - 2015/ english -> 2020)')
disp(' *********************************************')
disp(' ')
disp('***** Menu *****')
disp(' ')
disp(' 1 - Normal shock waves')
disp(' 2 - Oblique shock waves')
disp(' 3 - Isentropic compression and expansion')
disp(' 4 - Prandtl-Meyer func. omega = f( Mach )  (one value)')
disp(' 5 - Prandtl-Meyer func. Mach  = F( omega ) (one value)')
disp(' 6 - Isentropic ratios for a given Mach number')    
disp(' 7 - Figure omega = f( Mach )')    
disp(' 8 - Table  omega = f( Mach )')
disp(' 9 - Epicycloid')    
disp('10 - Shock curve and Busemann shock polar')
disp('11 - Multiple shock curves: 2D or 3D plots, plot for  M2 = 1 and max. deviation angle theta max ')
disp('12 - Shock : downstream unitary Mach  and maximal deviation angle for a given upstream Mach')
disp('13 - Exercise: shocks, 2 expansions + oblique shock')
disp('14 - Rayleigh function Ra( Mach )')
disp('15 - Inverted Rayleigh function Mach = f( Ra )')
disp('16 - Rayleigh problem')
disp('17 - Rayleigh curve')
disp('18 - Fanno function = Fa( Mach )')
disp('19 - inverted Fanno function Mach = f( Fa )')
disp('20 - Fanno problem')
disp('21 - Fanno flow rate')
end